# Generated by Django 5.2.5 on 2025-08-25 16:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_linkexterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='linkexterno',
            name='resumo',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Adicione um breve comentário ou resumo sobre o link.'),
        ),
    ]
